
package compiladores;

public enum Token {
    ID, PALAVRA_RESERVADA, LITERALCHAR, LITERALSTR, LITERALNUM, OPERADOR_ARITMETICO, OPERADOR_RELACIONAL,
    OPERADOR_LOGICO, OPERADOR_ATRIBUICAO, SIMBOLOS_PONTUACAO, ERROR
}